export enum Role {
    ADMIN = 'ADMIN',
    SUPPLIERS = 'SUPPLIERS',
    ADDITIONOFFICIAL = 'ADDITIONOFFICIAL',
    STOREKEPPER = 'STOREKEPPER',
    SUPERVISORYOFFICER = 'SUPERVISORYOFFICER',
    STOREMANAGER = 'STOREMANAGER',
    SECTION = 'SECTION',
    USER = "USER",
    DEFAULT = "DEFAULT",
}
